# Generated by Django 4.1.4 on 2022-12-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('batard', models.BooleanField(verbose_name='Batard')),
                ('nombatard', models.CharField(max_length=50, verbose_name='Batard')),
                ('isnoble', models.BooleanField()),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('deces', models.CharField(max_length=255, verbose_name='Mort')),
                ('enfants', models.ManyToManyField(to='api.perso')),
                ('epoux', models.ManyToManyField(to='api.perso')),
                ('geniteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Père', to='api.perso')),
                ('genitrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mère', to='api.perso')),
            ],
            options={
                'verbose_name': 'Perso ',
                'verbose_name_plural': 'Perso s',
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nommaison', models.CharField(max_length=50, verbose_name='Nom de la Maison')),
                ('banneret', models.ManyToManyField(related_name='Bannerets', to='api.maison')),
                ('membre', models.ManyToManyField(related_name='Bannerets', to='api.perso', verbose_name='Membres')),
                ('perso', models.ManyToManyField(to='api.perso')),
                ('suzerain', models.ManyToManyField(related_name='Suzerain Lige', to='api.maison')),
            ],
            options={
                'verbose_name': 'Maison ',
                'verbose_name_plural': 'Maisons',
            },
        ),
    ]
