# Generated by Django 4.1.4 on 2022-12-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='banneret',
            field=models.ManyToManyField(blank=True, related_name='Bannerets', to='api.maison'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='membre',
            field=models.ManyToManyField(blank=True, related_name='Bannerets', to='api.perso', verbose_name='Membres'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='perso',
            field=models.ManyToManyField(blank=True, to='api.perso'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='suzerain',
            field=models.ManyToManyField(blank=True, related_name='Suzerain Lige', to='api.maison'),
        ),
    ]
