# Generated by Django 4.1.4 on 2022-12-17 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_maison_banneret_alter_maison_membre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maison',
            options={'verbose_name': 'Maison', 'verbose_name_plural': 'Maisons'},
        ),
        migrations.AlterField(
            model_name='maison',
            name='nommaison',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom de la Maison'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='batard',
            field=models.BooleanField(blank=True, verbose_name='Batard'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='deces',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mort'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='geniteur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Père', to='api.perso'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='genitrice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mère', to='api.perso'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='isnoble',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perso',
            name='nom',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
