# Generated by Django 4.1.4 on 2022-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_maison_options_alter_maison_nommaison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='maison',
            field=models.ManyToManyField(blank=True, related_name="Maison d'appartenance+", to='api.perso'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='perso',
            field=models.ManyToManyField(blank=True, related_name='Membres de la maison+', to='api.perso'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='enfants',
            field=models.ManyToManyField(blank=True, to='api.perso'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='epoux',
            field=models.ManyToManyField(blank=True, to='api.perso'),
        ),
    ]
