# Generated by Django 4.1.4 on 2022-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_perso_maison_alter_maison_perso_alter_perso_enfants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='maison',
            field=models.ManyToManyField(blank=True, related_name="Maison d'appartenance+", to='api.maison'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='nombatard',
            field=models.CharField(blank=True, max_length=50, verbose_name='Batard'),
        ),
    ]
