# Generated by Django 4.1.4 on 2022-12-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_perso_maison_alter_perso_nombatard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='nom',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nom'),
        ),
    ]
