# Generated by Django 4.1.4 on 2022-12-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_perso_geniteur_alter_perso_genitrice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='perso',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='maison',
        ),
        migrations.AddField(
            model_name='perso',
            name='maison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="Maison d'appartenance+", to='api.maison'),
        ),
    ]
