# Generated by Django 4.1.4 on 2022-12-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_maison_perso_remove_perso_maison_perso_maison'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='maisonnaissance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Maison de naissance+', to='api.maison'),
        ),
    ]
