# Generated by Django 4.1.4 on 2022-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_perso_maisonnaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='membre',
            field=models.ManyToManyField(blank=True, related_name='Membres', to='api.perso', verbose_name='Membres'),
        ),
    ]
