# Generated by Django 4.1.4 on 2022-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_perso_geniteur_alter_perso_genitrice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='nom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom'),
        ),
    ]
