# Generated by Django 4.1.4 on 2022-12-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_perso_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='surnom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Surnom'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='nombatard',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom de Batard'),
        ),
    ]
