# Generated by Django 4.1.4 on 2022-12-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_maison_fief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='lieu',
            field=models.ManyToManyField(blank=True, related_name='Lieu', to='api.lieu'),
        ),
    ]
