# Generated by Django 4.1.4 on 2022-12-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_continent_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='fief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fief', to='api.lieu'),
        ),
    ]
