# Generated by Django 4.1.4 on 2022-12-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_maison_fief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='enfants',
        ),
    ]
