# Generated by Django 4.1.4 on 2022-12-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_perso_enfants'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='generation',
            field=models.IntegerField(null=True, verbose_name='Génération'),
        ),
    ]
